site_name: Apollinaire G. Beslon
nav:
  - Home: 'index.md'
  - Básně:
    - Pírka: "pirka.md"
    - "Francouzské kaligramy": "kaligramy.md"
  - Próza:
    - "povidky.md"

theme:
  name: mkdocs
  analytics:
    gtag: G-C1V59CKJPF

extra_css:
  - style.css

